-- Seed data for AS Events venues and packages

-- ---------------------------------------------------------------------------
-- Seed Venues
-- ---------------------------------------------------------------------------
INSERT INTO venues (id, slug, name, location, city, category, capacity, indoor_outdoor, rating, starting_price, image, description, parking, rooms, amenities, gallery, featured)
VALUES
  (
    '1',
    'royal-palace-wedding-hall-ahmedabad',
    'Royal Palace Wedding Hall',
    'SG Highway, Ahmedabad',
    'Ahmedabad',
    'Wedding Halls',
    '800 Guests',
    'Indoor',
    4.8,
    '₹2,50,000',
    'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=1200&auto=format&fit=crop',
    'A grand wedding hall featuring crystal chandeliers, marble flooring, and a spacious mandap area. Perfect for traditional Gujarati weddings with modern amenities and dedicated bridal suites.',
    '200+ Vehicles',
    '12 Bridal & Guest Rooms',
    '["AC Banquet Hall","In-house Catering","Bridal Suite","Valet Parking","Stage & Mandap","Green Room"]'::jsonb,
    '["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=800","https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800","https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=800"]'::jsonb,
    true
  ),
  (
    '2',
    'grand-banquet-surat',
    'Grand Imperial Banquet',
    'Athwa Lines, Surat',
    'Surat',
    'Banquet Halls',
    '600 Guests',
    'Indoor',
    4.6,
    '₹1,80,000',
    'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop',
    'An elegant banquet hall in the heart of Surat, ideal for weddings, receptions, and corporate dinners. Features state-of-the-art lighting and a professional kitchen team.',
    '150 Vehicles',
    '8 Guest Rooms',
    '["Multi-cuisine Catering","LED Stage","Sound System","Decor Support","Parking","AC Halls"]'::jsonb,
    '["https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800","https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=800","https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=800"]'::jsonb,
    false
  ),
  (
    '3',
    'azure-luxury-resort-udaipur',
    'Azure Luxury Resort',
    'Lake Pichola Road, Udaipur',
    'Udaipur',
    'Luxury Resorts',
    '500 Guests',
    'Indoor & Outdoor',
    4.9,
    '₹8,00,000',
    'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?q=80&w=1200&auto=format&fit=crop',
    'A breathtaking lakeside luxury resort offering destination wedding experiences with royal Rajasthani architecture, infinity pools, and panoramic lake views.',
    '100 Vehicles',
    '45 Luxury Suites',
    '["Lake View Venues","Spa & Wellness","Poolside Events","Royal Decor","Helipad Access","Butler Service"]'::jsonb,
    '["https://images.unsplash.com/photo-1544078751-58fee2d8a03b?q=80&w=800","https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=800","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800"]'::jsonb,
    true
  ),
  (
    '4',
    'heritage-palace-jaipur',
    'Heritage Palace Jaipur',
    'Amer Road, Jaipur',
    'Jaipur',
    'Destination Venues',
    '1,000 Guests',
    'Indoor & Outdoor',
    4.9,
    '₹12,00,000',
    'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop',
    'A magnificent heritage palace for royal destination weddings. Features courtyards, gardens, and opulent halls with authentic Rajasthani hospitality.',
    '250 Vehicles',
    '60 Heritage Rooms',
    '["Palace Courtyard","Elephant Procession","Royal Dining","Heritage Decor","Cultural Performances","Fireworks"]'::jsonb,
    '["https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800","https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=800","https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=800"]'::jsonb,
    false
  ),
  (
    '5',
    'green-meadows-farmhouse-vadodara',
    'Green Meadows Farmhouse',
    'Halol Road, Vadodara',
    'Vadodara',
    'Farmhouses',
    '400 Guests',
    'Outdoor',
    4.7,
    '₹1,20,000',
    'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=1200&auto=format&fit=crop',
    'A serene farmhouse venue surrounded by lush greenery, perfect for intimate weddings, mehendi functions, and outdoor celebrations under the stars.',
    '80 Vehicles',
    '6 Cottage Rooms',
    '["Open Lawn","Swimming Pool","Bonfire Area","Outdoor Kitchen","Tent Setup","Garden Decor"]'::jsonb,
    '["https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=800","https://images.unsplash.com/photo-1519167758481-83f550bb49b3?q=80&w=800","https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=800"]'::jsonb,
    true
  ),
  (
    '6',
    'sunset-beach-resort-goa',
    'Sunset Beach Resort',
    'Candolim Beach, Goa',
    'Goa',
    'Beach Venues',
    '300 Guests',
    'Outdoor',
    4.8,
    '₹5,00,000',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
    'A stunning beachfront resort for destination weddings with sunset ceremonies, beachside dining, and tropical decor amidst golden sands.',
    '60 Vehicles',
    '30 Beach Villas',
    '["Beach Ceremony Setup","Water Sports","Beachside Dining","Sunset Deck","Spa","Live Music Area"]'::jsonb,
    '["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800","https://images.unsplash.com/photo-1544078751-58fee2d8a03b?q=80&w=800","https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=800"]'::jsonb,
    false
  ),
  (
    '7',
    'metro-convention-centre-mumbai',
    'Metro Convention Centre',
    'Bandra Kurla Complex, Mumbai',
    'Mumbai',
    'Corporate Venues',
    '2,000 Guests',
    'Indoor',
    4.7,
    '₹4,00,000',
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1200&auto=format&fit=crop',
    'A premium corporate venue in Mumbai''s business district. Ideal for conferences, product launches, and award ceremonies with world-class AV and breakout rooms.',
    '500 Vehicles',
    '10 Meeting Rooms',
    '["AV & Projection","Breakout Rooms","High-speed WiFi","Business Lounge","Catering","Registration Desk"]'::jsonb,
    '["https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800","https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=800","https://images.unsplash.com/photo-1531058020387-3be344556be6?q=80&w=800"]'::jsonb,
    true
  ),
  (
    '8',
    'expo-grand-hall-delhi',
    'Expo Grand Hall',
    'Pragati Maidan, Delhi',
    'Delhi',
    'Exhibition Venues',
    '5,000 Guests',
    'Indoor',
    4.5,
    '₹6,00,000',
    'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop',
    'A sprawling exhibition hall designed for trade shows, expos, and large-scale corporate events with modular booth layouts and loading docks.',
    '1,000 Vehicles',
    '5 Conference Rooms',
    '["Exhibition Booths","Loading Docks","High Ceilings","Power Supply","Security","Food Courts"]'::jsonb,
    '["https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800","https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800","https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=800"]'::jsonb,
    false
  ),
  (
    '9',
    'emerald-open-lawn-pune',
    'Emerald Open Lawn',
    'Koregaon Park, Pune',
    'Pune',
    'Open Lawns',
    '700 Guests',
    'Outdoor',
    4.6,
    '₹1,50,000',
    'https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=1200&auto=format&fit=crop',
    'A beautifully landscaped open lawn venue perfect for sangeet nights, receptions, and garden weddings with flexible tent and stage options.',
    '120 Vehicles',
    '4 Changing Rooms',
    '["Open Lawn","Tent Setup","Stage Platform","Garden Lighting","Catering Area","Generator Backup"]'::jsonb,
    '["https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=800","https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=800","https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800"]'::jsonb,
    false
  ),
  (
    '10',
    'crystal-banquet-rajkot',
    'Crystal Banquet Hall',
    'Kalawad Road, Rajkot',
    'Rajkot',
    'Banquet Halls',
    '500 Guests',
    'Indoor',
    4.5,
    '₹1,40,000',
    'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=1200&auto=format&fit=crop',
    'A modern banquet hall in Rajkot with crystal-themed interiors, perfect for weddings, engagements, and corporate gatherings.',
    '100 Vehicles',
    '6 Guest Rooms',
    '["AC Hall","Crystal Lighting","In-house Decor","Catering","DJ Setup","Parking"]'::jsonb,
    '["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=800","https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=800","https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=800"]'::jsonb,
    false
  ),
  (
    '11',
    'riverside-wedding-pavilion-ahmedabad',
    'Riverside Wedding Pavilion',
    'Sabarmati Riverfront, Ahmedabad',
    'Ahmedabad',
    'Wedding Halls',
    '600 Guests',
    'Indoor & Outdoor',
    4.7,
    '₹2,00,000',
    'https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=1200&auto=format&fit=crop',
    'A scenic riverside wedding pavilion offering both indoor banquet and outdoor lawn spaces with stunning Sabarmati riverfront views.',
    '150 Vehicles',
    '10 Guest Rooms',
    '["River View","Indoor & Outdoor Spaces","Mandap Area","Catering","Valet","Bridal Suite"]'::jsonb,
    '["https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=800","https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800","https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=800"]'::jsonb,
    false
  ),
  (
    '12',
    'tech-hub-conference-pune',
    'Tech Hub Conference Centre',
    'Hinjewadi, Pune',
    'Pune',
    'Corporate Venues',
    '1,200 Guests',
    'Indoor',
    4.6,
    '₹3,00,000',
    'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=1200&auto=format&fit=crop',
    'A modern conference centre in Pune''s IT hub, equipped for tech summits, hackathons, and corporate town halls with hybrid event capabilities.',
    '300 Vehicles',
    '8 Meeting Rooms',
    '["Hybrid Streaming","AV Equipment","Breakout Spaces","Cafeteria","WiFi","Registration Area"]'::jsonb,
    '["https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=800","https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800","https://images.unsplash.com/photo-1531058020387-3be344556be6?q=80&w=800"]'::jsonb,
    false
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  city = EXCLUDED.city,
  category = EXCLUDED.category,
  capacity = EXCLUDED.capacity,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  rating = EXCLUDED.rating,
  starting_price = EXCLUDED.starting_price,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  parking = EXCLUDED.parking,
  rooms = EXCLUDED.rooms,
  amenities = EXCLUDED.amenities,
  gallery = EXCLUDED.gallery,
  featured = EXCLUDED.featured;

-- ---------------------------------------------------------------------------
-- Seed Packages
-- ---------------------------------------------------------------------------
INSERT INTO packages (id, slug, title, category, includes, included_services, highlights, suitable_guests, duration, price, popular, description)
VALUES
  (
    'haldi',
    'haldi-ceremony',
    'Haldi Ceremony',
    'wedding',
    '["Traditional Decor","Floral Arrangements","Seating Setup","Photography","Music System"]'::jsonb,
    '["Event planning & coordination","Venue liaison","Decor & floral design","Photography & videography","Entertainment coordination","Guest hospitality"]'::jsonb,
    '["Yellow theme decor","Traditional seating","Live dhol optional"]'::jsonb,
    '50 - 200',
    '4-6 hours',
    'Starting from ₹75,000',
    false,
    'A vibrant haldi ceremony with traditional aesthetics and joyful ambiance.'
  ),
  (
    'complete-wedding',
    'complete-wedding-package',
    'Complete Wedding Package',
    'wedding',
    '["Haldi","Mehendi","Sangeet","Baraat","Wedding","Reception"]'::jsonb,
    '["End-to-end wedding planning","All ceremony coordination","Premium decor & mandap","Photography & cinematography","Entertainment & DJ","Catering management","Guest hospitality"]'::jsonb,
    '["All ceremonies covered","Dedicated wedding manager","Premium vendor network"]'::jsonb,
    '300 - 1,000',
    '3-7 days',
    'Starting from ₹10,00,000',
    true,
    'The ultimate all-in-one wedding experience covering every ceremony from haldi to reception.'
  ),
  (
    'mehendi',
    'mehendi-ceremony',
    'Mehendi Ceremony',
    'wedding',
    '["Theme Decor","Mehendi Artists","Live Music","Food Counters","Photography"]'::jsonb,
    '["Event planning & coordination","Venue liaison","Decor & floral design","Photography & videography","Entertainment coordination","Guest hospitality"]'::jsonb,
    '["Colourful lounge setup","Artist coordination","Live folk music"]'::jsonb,
    '100 - 300',
    '5-7 hours',
    'Starting from ₹1,00,000',
    false,
    'A colourful mehendi celebration with artists, live music, and themed decor.'
  ),
  (
    'sangeet',
    'sangeet-night',
    'Sangeet Night',
    'wedding',
    '["Stage Design","LED Setup","DJ","Sound System","Dance Floor"]'::jsonb,
    '["Event planning & coordination","Venue liaison","Decor & floral design","Photography & videography","Entertainment coordination","Guest hospitality"]'::jsonb,
    '["Professional stage","LED backdrop","Choreography support"]'::jsonb,
    '200 - 600',
    '6-8 hours',
    'Starting from ₹2,00,000',
    false,
    'A high-energy sangeet night with professional stage, sound, and dance floor setup.'
  ),
  (
    'baarat',
    'baarat-management',
    'Baraat Management',
    'wedding',
    '["Procession Setup","Band & Dhol","Decorated Horse/Car","Lighting","Guest Coordination"]'::jsonb,
    '["Event planning & coordination","Venue liaison","Decor & floral design","Photography & videography","Entertainment coordination","Guest hospitality"]'::jsonb,
    '["Royal procession","Live band & dhol","VIP guest handling"]'::jsonb,
    '100 - 500',
    '3-5 hours',
    'Starting from ₹1,50,000',
    false,
    'A grand baarat procession with traditional music, decor, and seamless coordination.'
  ),
  (
    'reception',
    'reception-celebration',
    'Reception Celebration',
    'wedding',
    '["Luxury Stage","Lighting","Entertainment","Catering","Photography"]'::jsonb,
    '["Event planning & coordination","Venue liaison","Decor & floral design","Photography & videography","Entertainment coordination","Guest hospitality"]'::jsonb,
    '["Grand stage design","Premium lighting","Live entertainment"]'::jsonb,
    '300 - 1,000',
    '5-7 hours',
    'Starting from ₹2,50,000',
    false,
    'A grand reception with luxury staging, lighting, and premium entertainment.'
  ),
  (
    'corporate-conference',
    'corporate-conference',
    'Corporate Conference',
    'corporate',
    '["Agenda Planning","Venue & AV Setup","Registration Desk","Hospitality","Photography"]'::jsonb,
    '["Planning","Venue Coordination","Branding","AV Setup","Photography","Hospitality"]'::jsonb,
    '["Keynote production","Breakout sessions","Hybrid streaming ready"]'::jsonb,
    '100 - 1,200',
    '1-3 days',
    'Starting from ₹2,00,000',
    false,
    'Professional conference planning with branding, AV, and hospitality management.'
  ),
  (
    'product-launch',
    'product-launch',
    'Product Launch',
    'corporate',
    '["Branding & Stage","AV & Media Setup","VIP Hospitality","Photography","PR Coordination"]'::jsonb,
    '["Planning","Venue Coordination","Branding","AV Setup","Photography","Hospitality"]'::jsonb,
    '["Immersive branding","Media-ready production","Influencer zones"]'::jsonb,
    '150 - 800',
    '4-8 hours',
    'Starting from ₹3,50,000',
    false,
    'Impactful product launches with immersive branding and media-ready production.'
  ),
  (
    'awards-night',
    'awards-night',
    'Awards Night',
    'corporate',
    '["Stage Design","Lighting","Entertainment","Hospitality","Photography"]'::jsonb,
    '["Planning","Venue Coordination","Branding","AV Setup","Photography","Hospitality"]'::jsonb,
    '["Elegant staging","Award ceremony flow","Celebrity coordination"]'::jsonb,
    '200 - 1,000',
    '4-6 hours',
    'Starting from ₹2,50,000',
    false,
    'Prestigious award ceremonies with elegant staging and flawless hospitality.'
  ),
  (
    'team-building',
    'team-building-event',
    'Team Building Event',
    'corporate',
    '["Activity Planning","Venue Setup","Facilitation","Catering","Photography"]'::jsonb,
    '["Planning","Venue Coordination","Activity design","Catering","Photography"]'::jsonb,
    '["Custom activities","Outdoor & indoor options","Team engagement focus"]'::jsonb,
    '30 - 300',
    'Half / Full day',
    'Starting from ₹1,50,000',
    false,
    'Engaging team building experiences designed to strengthen collaboration and morale.'
  ),
  (
    'birthday',
    'birthday-celebration',
    'Birthday Celebration',
    'social',
    '["Theme Decor","Entertainment","Photography","Cake & Catering","Venue Setup"]'::jsonb,
    '["Planning","Decor & Styling","Entertainment","Photography","Catering"]'::jsonb,
    '["Custom themes","Photo booth add-on","Kids & adult packages"]'::jsonb,
    '30 - 300',
    '4-6 hours',
    'Starting from ₹75,000',
    false,
    'Memorable birthday parties with themed decor, entertainment, and photography.'
  ),
  (
    'anniversary',
    'anniversary-celebration',
    'Anniversary Celebration',
    'social',
    '["Elegant Decor","Live Music","Photography","Fine Dining","Memory Display"]'::jsonb,
    '["Planning","Decor & Styling","Entertainment","Photography","Catering"]'::jsonb,
    '["Romantic styling","Memory wall","Live musicians"]'::jsonb,
    '50 - 250',
    '4-6 hours',
    'Starting from ₹1,00,000',
    false,
    'Romantic anniversary celebrations with elegant styling and curated entertainment.'
  ),
  (
    'baby-shower',
    'baby-shower',
    'Baby Shower',
    'social',
    '["Theme Decor","Games & Activities","Catering","Photography","Favours"]'::jsonb,
    '["Planning","Decor","Entertainment","Photography","Catering"]'::jsonb,
    '["Pastel themes","Game coordination","Custom favours"]'::jsonb,
    '30 - 100',
    '3-5 hours',
    'Starting from ₹60,000',
    false,
    'Charming baby shower events with delightful decor and thoughtful hospitality.'
  ),
  (
    'housewarming',
    'housewarming-ceremony',
    'Housewarming Ceremony',
    'social',
    '["Traditional Decor","Pooja Setup","Catering","Photography","Guest Coordination"]'::jsonb,
    '["Planning","Decor","Catering","Photography","Hospitality"]'::jsonb,
    '["Traditional rituals","Home styling","Intimate gatherings"]'::jsonb,
    '30 - 150',
    '3-5 hours',
    'Starting from ₹50,000',
    false,
    'Warm housewarming celebrations with traditional decor and seamless coordination.'
  ),
  (
    'trade-exhibition',
    'trade-exhibition',
    'Trade Exhibition',
    'exhibition',
    '["Booth Design","Venue Coordination","Visitor Management","AV Setup","Branding"]'::jsonb,
    '["Planning","Booth fabrication","Branding","AV","Visitor hospitality"]'::jsonb,
    '["Custom booth design","Lead capture systems","Sponsor branding"]'::jsonb,
    '500 - 5,000',
    '2-5 days',
    'Starting from ₹5,00,000',
    false,
    'Large-scale trade exhibitions with professional booth design and visitor management.'
  ),
  (
    'expo-management',
    'expo-management',
    'Expo Management',
    'exhibition',
    '["Floor Planning","Exhibitor Coordination","Registration","AV & Lighting","Security Liaison"]'::jsonb,
    '["End-to-end expo planning","Vendor management","Branding","Operations"]'::jsonb,
    '["Multi-hall coordination","Exhibitor onboarding","Live operations desk"]'::jsonb,
    '1,000 - 10,000',
    '3-7 days',
    'Starting from ₹8,00,000',
    false,
    'Full expo management from floor planning to on-ground operations.'
  ),
  (
    'product-showcase',
    'product-showcase',
    'Product Showcase',
    'exhibition',
    '["Display Design","Lighting","Demo Zones","Branding","Photography"]'::jsonb,
    '["Planning","Display fabrication","Branding","AV","Media"]'::jsonb,
    '["Interactive demo zones","Product-focused staging","Media lounge"]'::jsonb,
    '100 - 500',
    '1-3 days',
    'Starting from ₹2,50,000',
    false,
    'Focused product showcases with immersive display design and demo experiences.'
  ),
  (
    'live-concert',
    'live-concert',
    'Live Concert',
    'entertainment',
    '["Stage Production","Sound & Lighting","Artist Coordination","Security","Crowd Management"]'::jsonb,
    '["Production","Technical crew","Artist liaison","Safety & crowd control"]'::jsonb,
    '["Professional stage","Concert-grade sound","Artist hospitality"]'::jsonb,
    '500 - 10,000',
    '4-6 hours',
    'Starting from ₹5,00,000',
    false,
    'Large-scale live concerts with professional production and crowd management.'
  ),
  (
    'celebrity-night',
    'celebrity-night',
    'Celebrity Night',
    'entertainment',
    '["Celebrity Booking","Stage Design","VIP Hospitality","Security","Media Management"]'::jsonb,
    '["Celebrity coordination","Production","VIP hosting","Security"]'::jsonb,
    '["Celebrity appearances","Red carpet setup","VIP lounge"]'::jsonb,
    '200 - 2,000',
    '3-5 hours',
    'Starting from ₹8,00,000',
    false,
    'Exclusive celebrity nights with premium hospitality and flawless production.'
  ),
  (
    'cultural-festival',
    'cultural-festival',
    'Cultural Festival',
    'entertainment',
    '["Stage & Lighting","Entertainment","Food Counters","Crowd Management","Decor"]'::jsonb,
    '["Festival planning","Entertainment booking","Operations","Safety"]'::jsonb,
    '["Multi-stage setup","Cultural performances","Food festival zones"]'::jsonb,
    '500 - 5,000',
    '1-3 days',
    'Starting from ₹3,00,000',
    false,
    'Vibrant cultural festivals with multi-stage entertainment and crowd coordination.'
  )
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  includes = EXCLUDED.includes,
  included_services = EXCLUDED.included_services,
  highlights = EXCLUDED.highlights,
  suitable_guests = EXCLUDED.suitable_guests,
  duration = EXCLUDED.duration,
  price = EXCLUDED.price,
  popular = EXCLUDED.popular,
  description = EXCLUDED.description;
